#!/usr/bin/env bash

#-------------------------------------------------------------------
# Script options and handlers
#-------------------------------------------------------------------
trap '__cleanup__' EXIT

#-------------------------------------------------------------------
# Variable and functions
#-------------------------------------------------------------------
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
init_dir="${PWD}"

source "${script_dir}/include/functions.sh"
source "${script_dir}/include/custom.sh"
source "${script_dir}/include/software.sh"

final_msg="Check possible errors in '${error}'

  • Check how to install 'zsh'
    https://bit.ly/3Tz6zLO

  • You could need the thunderbird-menu-fix
    libdbusmenu-glib4 (Install)

  • Custom Grub themes
    https://github.com/vinceliuice/grub2-themes"

#-------------------------------------------------------------------
# Execution
#-------------------------------------------------------------------

# Check root password has been entered
if ! sudo -n true 2> /dev/null; then

  # Ask for root password
  while true; do
    # If propmt is canceled, exit
    if ! password=$(whiptail --passwordbox "Type your sudo password" --title "sudo password" \
      8 60 3>&1 1>&2 2>&3)
    then
      whiptail --title "🔒 Goodbye! 🔒" --msgbox 'sudo password no provided' 7 60
      exit 1
    fi

    # If password is correct, stop asking
    if sudo -S true 2> /dev/null <<< "${password}"; then
      break
    fi
  done
fi

# New date for log
if [ ! -f "${error}" ]; then
  echo -e "+++++++++++++++ $(date +'%x %X') +++++++++++++++" >> "${error}"
else
  echo -e "\n+++++++++++++++ $(date +'%x %X') +++++++++++++++" >> "${error}"
fi

# Set software's installation statuses
check_software

# Display software's statuses
if ! pre_installation; then
  final_message "${final_msg}"
  exit
fi

installation

final_message "${final_msg}"
