#!/usr/bin/env bash
set -eE
trap '__error_handling__; exit' ERR
trap 'tput cnorm; cd "${init_dir}"' EXIT

current_pkg_name=
init_dir="${PWD}"
error="${HOME}/error.log"

__error_handling__() {
  whiptail --title "❗ $current_pkg_name ❗" --msgbox 'Installation failed\n\nCheck the error.log' 9 60
}

#-------------------------------------------------------------------
# Display the final message or the error log given the user's choice
#-------------------------------------------------------------------
# @arg $1 Message
#-------------------------------------------------------------------
final_message() {

  if (whiptail --title 'Goodbye!' --scrolltext --yesno "$1" --yes-button 'Show error log' \
      --no-button 'Exit' --defaultno 15 80)
  then
    whiptail --title 'Error log file' --scrolltext --textbox "${error}" 15 80
  fi
}

#-------------------------------------------------------------------
# Append a separator in the error log with the name of the package
#-------------------------------------------------------------------
# @arg $1 Name of the package
# @arg $2 Target file
#-------------------------------------------------------------------
log_separator() {
  echo -e "---------------$1---------------" >> "${error}"
}

#-------------------------------------------------------------------
# Display infobox with a spinner showing that a process is running
#-------------------------------------------------------------------
# @arg $1 Command to be executed
# @arg $2 Title of the infobox
# @arg $3 Message of the infobox
#-------------------------------------------------------------------
infobox_spinner() {
  local frames=('▰ ▱ ▱ ▱ ▱' '▱ ▰ ▱ ▱ ▱' '▱ ▱ ▰ ▱ ▱' '▱ ▱ ▱ ▰ ▱' '▱ ▱ ▱ ▱ ▰')

  tput civis # cursor invisible

  local pid=$1

  while kill -0 "${pid}" 2&> /dev/null; do
    local i=$(( (i + 1) % ${#frames[@]} ))
    TERM=ansi; whiptail --title "🔨 $2 🔨" --infobox "$3\n${frames[$i]}" 9 60; TERM=xterm-256color
    sleep 0.1
  done

  tput cnorm # cursor back to normal
  wait "${pid}" # capture exit code
  return $?
}

#-------------------------------------------------------------------
# Install package from default repository
#-------------------------------------------------------------------
# @arg $1 Human-readable name of the package
# @arg $2 Name of the package
# @arg $3 Installed?
#
# @example
#   install_standard "Yakuake" "yakuake" "${is_installed_yakuake}"
#-------------------------------------------------------------------
install_standard() {
  if $3; then return; fi

  if (! whiptail --title "🚀 $1 🚀" --yesno "Do you want to install '$1'?" --defaultno 9 60); then
    whiptail --title "❌ $1 ❌" --msgbox 'Installation canceled' 9 60
    return
  fi

  log_separator "$1"
  current_pkg_name="$1"

  # Installation
  sudo apt-get install "$2" -qq > /dev/null 2>> "${error}" &
  infobox_spinner $! "$1" 'Installing'

  whiptail --title "✅ $1 ✅" --msgbox 'Installation completed' 9 60
}

#-------------------------------------------------------------------
# Install package from PPA
#-------------------------------------------------------------------
# @arg $1 Human-readable name of the package
# @arg $2 Name of the package
# @arg $3 PPA
# @arg $4 Installed?
#
# @example
#   install_PPA "git" "git" "ppa:git-core/ppa" "${is_installed_git}"
#-------------------------------------------------------------------
install_PPA() {
  if $4; then return; fi

  if (! whiptail --title "🚀 $1 🚀" --yesno "Do you want to install '$1'?" --defaultno 9 60); then
    whiptail --title "❌ $1 ❌" --msgbox 'Installation canceled' 9 60
    return
  fi

  log_separator "$1"
  current_pkg_name="$1"

  # PPA set up
  sudo add-apt-repository -y "$3" > /dev/null 2>> "${error}" &
  infobox_spinner $! "$1" 'Setting PPA'

  # Update
  sudo apt-get update -qq > /dev/null 2>> "${error}" &
  infobox_spinner $! "$1" 'Updating packages'

  # Installation
  sudo apt-get install "$2" -qq > /dev/null 2>> "${error}" &
  infobox_spinner $! "$1" "Installing $2"

  whiptail --title "✅ $1 ✅" --msgbox 'Installation completed' 9 60
}

#-------------------------------------------------------------------
# Install the package from the downloaded DEB file
#-------------------------------------------------------------------
# @arg $1 Human-readable name of the package
# @arg $2 URL of DEB file
# @arg $3 Indicates if it needs to consider redirects
# @arg $4 Installed?
#
# @example
#   install_deb "Chrome" "${chrome_url}" false "${is_installed_chrome}"
#   install_deb "VSCode" "${code_url}" true "${is_installed_code}"
#-------------------------------------------------------------------
install_deb() {
  if $4; then return; fi

  if (! whiptail --title "🚀 $1 🚀" --yesno "Do you want to install '$1'?" --defaultno 9 60); then
    whiptail --title "❌ $1 ❌" --msgbox 'Installation canceled' 9 60
    return
  fi

  log_separator "$1"
  current_pkg_name="$1"

  local url

  # Handle redirects
  if $3; then
    url=$(curl -w "%{url_effective}\n" -I -L -s -S "$2" -o /dev/null)
  else
    url="$2"
  fi

  # Download
  cd '/tmp' 2>> "${error}" || return
  curl -fsSLO "${url}" 2>> "${error}" &
  infobox_spinner $! "$1" 'Downloading'

  # Installation
  sudo apt-get install "./$(basename "${url}")" -qq > /dev/null 2>> "${error}" &
  infobox_spinner $! "$1" 'Installing'

  cd "${init_dir}" 2>> "${error}" || return
  whiptail --title "✅ $1 ✅" --msgbox 'Installation completed' 9 60
}
